services:
  - type: web
    name: url-shortener-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        value: TZHYviBKOZ5lxf91DcaUJkMakGlY9Yo_xNb8rls5KO4
      - key: FRONTEND_URL
        value: https://url-shortner-6d4v.onrender.com
      - key: ADMIN_IPS
        value: 127.0.0.1,::1
    autoDeploy: true
